# Generated by Django 2.2 on 2019-04-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20190417_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisationinfo',
            old_name='orgnisation_name',
            new_name='organisation_name',
        ),
    ]
